### Gradient Descent for Linear Regression Demo

In [1]:
import sklearn 
from sklearn import feature_extraction as fe
import os
import sys
import numpy as np
import pandas as pd

Step 1:  Load the data

In [37]:
 rawFrame = pd.read_csv("/data/FFIE.csv", low_memory=False)

In [39]:
print(rawFrame.columns)
print(rawFrame.shape)

Index(['Total Household Income', 'Region', 'Total Food Expenditure',
       'Main Source of Income', 'Agricultural Household indicator',
       'Bread and Cereals Expenditure', 'Total Rice Expenditure',
       'Meat Expenditure', 'Total Fish and  marine products Expenditure',
       'Fruit Expenditure', 'Vegetables Expenditure',
       'Restaurant and hotels Expenditure', 'Alcoholic Beverages Expenditure',
       'Tobacco Expenditure', 'Clothing, Footwear and Other Wear Expenditure',
       'Housing and water Expenditure', 'Imputed House Rental Value',
       'Medical Care Expenditure', 'Transportation Expenditure',
       'Communication Expenditure', 'Education Expenditure',
       'Miscellaneous Goods and Services Expenditure',
       'Special Occasions Expenditure', 'Crop Farming and Gardening expenses',
       'Total Income from Entrepreneurial Acitivites', 'Household Head Sex',
       'Household Head Age', 'Household Head Marital Status',
       'Household Head Highest Grade Compl

In [48]:
data = np.array([np.ones(rawFrame.shape[0]),rawFrame['Bread and Cereals Expenditure'], rawFrame['Total Rice Expenditure'],
                rawFrame['Meat Expenditure'], rawFrame['Fruit Expenditure'], rawFrame['Vegetables Expenditure']]).T

data

array([[  1.00000000e+00,   4.21400000e+04,   3.83000000e+04,
          2.46760000e+04,   3.32500000e+03,   1.34600000e+04],
       [  1.00000000e+00,   1.73290000e+04,   1.30080000e+04,
          1.74340000e+04,   2.03500000e+03,   7.83300000e+03],
       [  1.00000000e+00,   3.41820000e+04,   3.20010000e+04,
          7.78300000e+03,   1.73000000e+03,   3.79500000e+03],
       ..., 
       [  1.00000000e+00,   2.86460000e+04,   2.73390000e+04,
          4.80000000e+02,   1.23200000e+03,   3.02500000e+03],
       [  1.00000000e+00,   2.99960000e+04,   2.66550000e+04,
          2.35900000e+03,   2.92300000e+03,   7.95100000e+03],
       [  1.00000000e+00,   4.34850000e+04,   4.12050000e+04,
          1.98500000e+03,   2.06200000e+03,   7.11400000e+03]])

In [55]:
y = np.array([rawFrame['Total Household Income']]).T
y

array([[480332],
       [198235],
       [ 82785],
       ..., 
       [133171],
       [129500],
       [128598]])

Step 2. Linear regression

In [60]:

# d is the matrix

ddt = np.matmul(data.T,data)

rightHand = np.dot(data.T,y)

print(ddt)
print(rightHand)


beta = np.matmul(np.linalg.inv(ddt),rightHand)


[[  4.15440000e+04   1.04415542e+09   7.55927354e+08   4.37876775e+08
    1.05956933e+08   2.08007425e+08]
 [  1.04415542e+09   3.37771773e+13   2.47482809e+13   1.30420484e+13
    3.04330262e+12   5.87270578e+12]
 [  7.55927354e+08   2.47482809e+13   1.94680389e+13   9.06732242e+12
    2.09830039e+12   4.15990443e+12]
 [  4.37876775e+08   1.30420484e+13   9.06732242e+12   9.19338664e+12
    1.65992316e+12   2.87510321e+12]
 [  1.05956933e+08   3.04330262e+12   2.09830039e+12   1.65992316e+12
    6.36626178e+11   7.08949470e+11]
 [  2.08007425e+08   5.87270578e+12   4.15990443e+12   2.87510321e+12
    7.08949470e+11   1.49392756e+12]]
[[  1.02844492e+10]
 [  3.02879475e+14]
 [  2.09842700e+14]
 [  1.79354361e+14]
 [  4.21197503e+13]
 [  6.61726362e+13]]


In [61]:
beta

array([[  1.46609766e+04],
       [  2.95780819e+00],
       [ -2.12930473e+00],
       [  1.14585824e+01],
       [  2.24216064e+01],
       [  3.86231460e+00]])

### Gradient Descent

In [ ]:
## pick initial approximation

## select learning rate


## select Number of iterations


## compute next approximation




### Stochastic Gradient Descent

In [62]:
## pick initial approximation

## select learning rate


## select Number of iterations


## compute next approximation
